extends RefCounted
# Faz 3 — DATA içerik çevirileri (joker/boss/voucher/enhancement ad+açıklama). Kaynak Türkçe
# metni ANAHTAR; loc.gd t() bunu da yoklar. Joker ad/açıklamaları DÜZ Label/bbcode'da gösterilir.

const EN_DATA := {
	# ── Jokerler (ad + açıklama) ──
	"Sesli Avcısı": "Vowel Hunter",
	"Kelimedeki her sesli harf için +2 Çarpan.": "+2 Mult for each vowel in the word.",
	"İkizler": "Twins",
	"Tekrar eden her harf çifti için +15 Çip.": "+15 Chips for each repeated letter pair.",
	"Köşe Taşı": "Cornerstone",
	"Kelimenin ilk ve son harfi aynıysa +30 Çip.": "+30 Chips if the first and last letter match.",
	"Cimri": "Miser",
	"3 harf ve altı kelimeler ×3 Çarpan.": "Words of 3 letters or fewer: ×3 Mult.",
	"Mimar": "Architect",
	"6+ harfli kelime: harf sayısı × 6 Çip.": "6+ letter word: letter count × 6 Chips.",
	"Türkçe Belası": "Wordsmith's Curse",
	"8+ harfli kelime: +60 Çip ve +5 Çarpan.": "8+ letter word: +60 Chips and +5 Mult.",
	"Zincir": "Chain",
	"Bu turda her kelime bir öncekinden uzunsa +4 Çarpan.": "+4 Mult if each word this round is longer than the last.",
	"Kumarbaz": "Gambler",
	"Her kelimede %50 ihtimalle ×2 Çarpan.": "50% chance of ×2 Mult on each word.",
	"Simbiyoz": "Symbiosis",
	"Her sesli için +3 Çip, her sessiz için +1 Çarpan.": "+3 Chips per vowel, +1 Mult per consonant.",
	"Borsa": "Stock Market",
	"Paran her 6 birim için +1 Çarpan.": "+1 Mult for every 6 Money you have.",
	"Palindrom Tanrısı": "Palindrome God",
	"Palindrom kelime (tersten aynı): ×10 Çarpan!": "Palindrome word (same reversed): ×10 Mult!",
	"Harf Simyacısı": "Letter Alchemist",
	"Oynadığın her 'A' bu jokeri KALICI +1 Çarpan büyütür (tavan +25).": "Each 'A' played grows this Joker by a PERMANENT +1 Mult (cap +25).",
	"Anagram Şeytanı": "Anagram Demon",
	"Bu turda daha önce oynadığın bir kelimenin anagramını oynarsan ×3 Çarpan.": "×3 Mult if you play an anagram of a word already played this round.",
	"Sonsuz": "Infinity",
	"Tur skoru 1000'i geçtiyse kalan kelimelerde ×2 Çarpan.": "×2 Mult on remaining words once round score passes 1000.",
	"İntikam": "Vengeance",
	"Attığın her harf, SIRADAKİ kelimene +5 Çip ekler.": "Each letter you discard adds +5 Chips to your NEXT word.",
	"Çığ": "Avalanche",
	"Geçtiğin her tur için kalıcı +1 Çarpan (oyun boyunca büyür).": "Permanent +1 Mult per round cleared (grows all run).",
	"Yankı": "Echo",
	"Kelimenin ilk harfinin çip değeri bir kez daha sayılır.": "The first letter's chip value is counted again.",
	"Altın Kalem": "Golden Pen",
	"Her oynanan kelime +2 Para kazandırır.": "Each word played earns +2 Money.",
	"Kütüphaneci": "Librarian",
	"Kelimedeki her BENZERSIZ harf için +4 Çip.": "+4 Chips for each UNIQUE letter in the word.",
	"Sözlük Kurdu": "Bookworm",
	"Bu turda oynadığın her kelime için +2 Çarpan (tur başında sıfırlanır).": "+2 Mult per word played this round (resets each round).",
	"Heceleyici": "Speller",
	"5+ harfli kelime: +18 Çip.": "5+ letter word: +18 Chips.",
	"Tılsım": "Talisman",
	"Kelimede nadir harf (J, Ğ, F, V, Ö) varsa +5 Çarpan.": "+5 Mult if the word has a rare letter (J, Ğ, F, V, Ö).",
	"Ahenk": "Harmony",
	"Sesli–sessiz tam dönüşümlü dizilen kelime: ×2 Çarpan.": "Word that perfectly alternates vowel-consonant: ×2 Mult.",
	"Sayaç": "Counter",
	"Oynadığın her kelime bu jokeri KALICI +3 Çip büyütür (tavan +150).": "Each word played grows this Joker by a PERMANENT +3 Chips (cap +150).",
	"Tutumlu": "Thrifty",
	"Kalan her DEĞİŞİM hakkı için +12 Çip.": "+12 Chips for each DISCARD remaining.",
	"Çıkmaz": "Dead End",
	"Değişim hakkın hiç kalmadıysa +12 Çarpan.": "+12 Mult if you have no discards left.",
	"Mürekkep": "Ink",
	"Destede kalan her harf için +1 Çip.": "+1 Chips for each letter left in the deck.",
	"Telgraf": "Telegraph",
	"Oynanan her 'A' ve 'E' için +5 Çip ve +1 Çarpan.": "+5 Chips and +1 Mult for each 'A' and 'E' played.",
	"Dörtgen": "Quad",
	"Tam 4 harfli kelime: +30 Çip.": "Exactly 4-letter word: +30 Chips.",
	"Madenci": "Miner",
	"Çip değeri 5+ olan her harf için +15 Çip (G H P F Ö V Ğ J).": "+15 Chips for each letter worth 5+ chips (G H P F Ö V Ğ J).",
	"İkili": "Duo",
	"Kelimede aynı harften en az 2 tane varsa ×2 Çarpan.": "×2 Mult if any letter appears at least twice.",
	"Denge": "Balance",
	"Kelimede en az 3 sesli VE en az 3 sessiz varsa ×2 Çarpan.": "×2 Mult if the word has at least 3 vowels AND 3 consonants.",
	"Topluluk": "Collective",
	"Sahip olduğun her joker için +2 Çarpan.": "+2 Mult for each Joker you own.",
	"Patlamış Mısır": "Popcorn",
	"+20 Çarpan, ama geçtiğin her tur −4 (0'da tükenir).": "+20 Mult, but −4 each round cleared (spent at 0).",
	"Mürekkep Lekesi": "Inkblot",
	"Her kelimede +0 ila +20 arası rastgele Çarpan.": "Random +0 to +20 Mult on each word.",
	"Geri Dönüşüm": "Recycle",
	"Değiştirdiğin (attığın) her harf +1 Para kazandırır.": "Each letter you discard earns +1 Money.",
	"Kâtip": "Scribe",
	"Kelimenin İLK harfinin çip değeri 3 katı sayılır.": "The FIRST letter's chip value is counted triple.",
	"Sesli Tüccarı": "Vowel Merchant",
	"Kelimedeki her sesli harf için +6 Çip.": "+6 Chips for each vowel in the word.",
	"Hattat": "Calligrapher",
	"Kelimedeki her sessiz harf için +4 Çip.": "+4 Chips for each consonant in the word.",
	"Çifte Sessiz": "Double Consonant",
	"Yan yana her sessiz harf çifti için +12 Çip.": "+12 Chips for each adjacent consonant pair.",
	"Sesli Kümesi": "Vowel Cluster",
	"Yan yana her sesli harf çifti için +10 Çip.": "+10 Chips for each adjacent vowel pair.",
	"Uzun Soluk": "Long Breath",
	"7+ harfli kelime: ×2 Çarpan.": "7+ letter word: ×2 Mult.",
	"Kısa ve Öz": "Short & Sweet",
	"2–3 harfli kelime: +40 Çip.": "2-3 letter word: +40 Chips.",
	"Noktalama": "Punctuation",
	"Kelimenin SON harfinin çip değeri 2 katı sayılır.": "The LAST letter's chip value is counted double.",
	"Eşsiz": "Unique",
	"6+ harf ve tüm harfler farklıysa ×2 Çarpan.": "×2 Mult if 6+ letters and all are different.",
	"Cevher": "Gem",
	"En yüksek çipli harfin değeri bir kez daha eklenir.": "The highest-chip letter's value is added again.",
	"Çifte Dikiş": "Double Stitch",
	"Aynı harften 3 veya daha fazla varsa +60 Çip.": "+60 Chips if any letter appears 3 or more times.",
	"İlk Hamle": "First Move",
	"Turun İLK kelimesinde ×2 Çarpan.": "×2 Mult on the FIRST word of the round.",
	"Banker": "Banker",
	"Paran 20 veya üzeriyse +40 Çip.": "+40 Chips if you have 20 or more Money.",
	"Z Faktörü": "Z Factor",
	"Kelimede C, Ç, Ş veya Z varsa +25 Çip.": "+25 Chips if the word has C, Ç, Ş or Z.",
	"Sözlük Faresi": "Dictionary Mouse",
	"5 veya daha fazla farklı harf varsa +5 Çarpan.": "+5 Mult if the word has 5 or more different letters.",
	"Denge Bekçisi": "Balance Keeper",
	"Sesli ve sessiz harf sayısı eşitse ×2 Çarpan.": "×2 Mult if vowels and consonants are equal in number.",
	"Çırak": "Apprentice",
	"+30 Çip, ama geçtiğin her tur −5 (0'da tükenir).": "+30 Chips, but −5 each round cleared (spent at 0).",
	"Kronik": "Chronicle",
	"Geçtiğin her tur için +8 Çip (oyun boyunca büyür).": "+8 Chips per round cleared (grows all run).",
	"Tek Tip": "Parity",
	"Harf sayısı tekse +20 Çip; çiftse +2 Çarpan.": "Odd letter count: +20 Chips; even: +2 Mult.",
	"Sondaj": "Drill",
	"Çip değeri 7+ olan her harf için +25 Çip (F Ö V Ğ J).": "+25 Chips for each letter worth 7+ chips (F Ö V Ğ J).",
	"Ritim": "Rhythm",
	"Tam 5 harfli kelime: +28 Çip.": "Exactly 5-letter word: +28 Chips.",
	"Ünlü Uyumu": "Vowel Harmony",
	"Tüm sesliler ya kalın (A I O U) ya ince (E İ Ö Ü) ise ×2 Çarpan.": "×2 Mult if all vowels are back (A I O U) or all front (E İ Ö Ü).",
	"Çaylak Kalem": "Rookie Pen",
	"Her oynanan kelime +4 Çip ve +1 Para.": "Each word played: +4 Chips and +1 Money.",
	"Çift Kanat": "Twin Wings",
	"Sesli ve sessiz sayısı farkı en çok 1 ise +20 Çip.": "+20 Chips if vowel and consonant counts differ by at most 1.",
	"Mihenk": "Touchstone",
	"3 veya daha fazla FARKLI sesli türü varsa ×2 Çarpan.": "×2 Mult if the word has 3 or more DIFFERENT vowels.",
	"Tasarruf": "Frugal",
	"Hiç paran yoksa (0) +6 Çarpan.": "+6 Mult if you have no Money (0).",
	# ── Bosslar (ad + açıklama) ──
	"Uzun Yol": "Long Road",
	"Kelimeler en az 5 harf olmalı.": "Words must be at least 5 letters.",
	"Tekel": "Monopoly",
	"Aynı harf bir kelimede 2'den fazla kullanılamaz.": "No letter may be used more than twice in a word.",
	"Açgözlü": "Greedy",
	"Bu turda değişim (atma) hakkın yok.": "No discards this round.",
	"Darboğaz": "Bottleneck",
	"Bu turda bir kelime hakkın eksik.": "One fewer word play this round.",
	"Kısırlık": "Barren",
	"İlk oynadığın kelime sayılmaz (0 puan).": "Your first word scores nothing (0 points).",
	"Vergi": "Tax",
	"Her kelimede çarpanın yarısı vergi olarak alınır (×0.5).": "Half your Mult is taxed on every word (×0.5).",
	"Sansür": "Censor",
	"Rastgele 3 harf bu turda kilitli (kullanılamaz).": "3 random letters are locked this round (unusable).",
	"Maraton": "Marathon",
	"Hedef bu turda %30 daha yüksek.": "Target is 30% higher this round.",
	"Lanet": "Curse",
	"Her kelimeden 25 Çip eksilir.": "−25 Chips on every word.",
	"Buzul": "Glacier",
	"Her kelimede çipler yarıya iner.": "Chips are halved on every word.",
	"Cendere": "Vise",
	"Tek uzunlukta (3,5,7…) kelimeler ×0.5 çarpan.": "Odd-length words (3,5,7…) get ×0.5 Mult.",
	"Bir kelimeyi bu turda iki kez oynayamazsın.": "You can't play the same word twice this round.",
	# ── Vouchers (ad + açıklama) ──
	"Bol El": "Big Hand",
	"El boyutu kalıcı +1 (8 → 9 harf).": "Hand size permanently +1 (8 → 9 letters).",
	"Ekstra Hak": "Extra Play",
	"Kelime hakkı kalıcı +1 (her turda).": "Word plays permanently +1 (every round).",
	"Bol Atma": "Big Discard",
	"Atma hakkı kalıcı +1 (her turda).": "Discards permanently +1 (every round).",
	"Faizci": "Usurer",
	"Faiz tavanı +3 (daha çok tasarruf geliri).": "Interest cap +3 (more income from savings).",
	# ── Enhancements (ad + desc) ──
	"Yaldız": "Foil",
	"+50 Çip": "+50 Chips",
	"Holografik": "Holographic",
	"+10 Çarpan": "+10 Mult",
	"Polikrom": "Polychrome",
	"×1.5 Çarpan": "×1.5 Mult",
	"Altın": "Gold",
	"Oynanınca +3 Para": "+3 Money when played",
	"Cam": "Glass",
	"×2 Çarpan, %25 kırılır": "×2 Mult, 25% chance to shatter",
}
